import { userDocumentsRouter } from "./routes/user-documents.routes.js";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import { environment } from "./config/env.js";
import { authRouter } from "./routes/auth.routes.js";
import { newsletterRouter } from "./routes/newsletter.routes.js";
import { contactRouter } from "./routes/contact.routes.js";
import { tenantRouter } from "./routes/tenant.routes.js";
import { managementRouter } from "./routes/management.routes.js";
import { errorHandler, notFoundHandler } from "./middleware/error-handler.js";
import { healthRouter } from "./routes/health.routes.js";
import { transportRouter } from "./routes/transport.routes.js";
import { bookingRouter } from "./routes/booking.routes.js";
import { financeRouter } from "./routes/finance.routes.js";
import { stage4Router } from "./routes/stage4.routes.js";
import { rolesRouter } from "./routes/roles.routes.js";
import { bulkRouter } from "./routes/bulk.routes.js";
import { requireSameOrigin } from "./middleware/csrf.js";
import { generalLimit } from "./middleware/rate-limit.js";
import { auditPlatformMutation } from "./middleware/security-audit.js";
import { privacyRouter } from "./routes/privacy.routes.js";

export const app = express();

app.disable("x-powered-by");
app.set("trust proxy", "loopback");
app.use(helmet());
app.use(cors({ origin: environment.WEB_URL, credentials: true }));
app.use(express.json({ limit: "2mb" }));
app.use((_request, response, next) => { response.setHeader("Cache-Control", "no-store"); next(); });
app.use(requireSameOrigin);
app.use("/api", generalLimit);
app.use("/api", auditPlatformMutation);
app.use((request, response, next) => {
  const startedAt = performance.now();
  response.on("finish", () => {
    const durationMs = Math.round(performance.now() - startedAt);
    const message = `${request.method} ${request.path} ${response.statusCode} ${durationMs}ms`;
    if (durationMs >= 1000) console.warn(`[slow api] ${message}`);
    else console.info(`[api] ${message}`);
  });
  next();
});
app.use("/api/health", healthRouter);
app.use("/api", privacyRouter);
app.use("/api/auth", authRouter);
app.use("/api/newsletter", newsletterRouter);
app.use("/api/contact", contactRouter);
app.use("/api/tenants", tenantRouter);
app.use("/api", managementRouter);
app.use("/api", userDocumentsRouter);
app.use("/api", transportRouter);
app.use("/api", bookingRouter);
app.use("/api", financeRouter);
app.use("/api", stage4Router);
app.use("/api", rolesRouter);
app.use("/api", bulkRouter);
app.use(notFoundHandler);
app.use(errorHandler);
