"use client";

import Link from "next/link";
import { useState } from "react";
import { z } from "zod";
import { requestPasswordReset, resetPassword, verifyPasswordResetOtp } from "../../src/features/auth/services/api-client";
import { Button } from "../../src/ui/Button";
import { Card } from "../../src/ui/Card";
import { Input } from "../../src/ui/Input";

const emailSchema = z.string().email("Enter a valid email address");
const passwordSchema = z.string().min(8, "Password must be at least 8 characters");
export default function ForgotPasswordPage() {
  const [step, setStep] = useState(0); const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [passwordConfirmation, setPasswordConfirmation] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submitEmail(event: React.FormEvent) { event.preventDefault(); const result = emailSchema.safeParse(email); if (!result.success) { setError(result.error.issues[0]?.message ?? "Enter a valid email"); return; } setLoading(true); setError(""); try { await requestPasswordReset(email); setStep(1); setNotice("If an account exists for this email, a reset code has been sent."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to send reset code"); } finally { setLoading(false); } }
  async function submitOtp(event: React.FormEvent) { event.preventDefault(); if (!/^\d{6}$/.test(otp)) { setError("Enter the 6-digit code from your email"); return; } setLoading(true); setError(""); try { await verifyPasswordResetOtp(email, otp); setStep(2); } catch (cause) { setError(cause instanceof Error ? cause.message : "The code is invalid or expired"); } finally { setLoading(false); } }
  async function submitPassword(event: React.FormEvent) { event.preventDefault(); const result = passwordSchema.safeParse(password); if (!result.success) { setError(result.error.issues[0]?.message ?? "Choose a stronger password"); return; } if (password !== passwordConfirmation) { setError("Passwords do not match"); return; } setLoading(true); setError(""); try { await resetPassword(email, otp, password); setStep(3); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to reset password"); } finally { setLoading(false); } }
  return <div className="login-page"><div className="login-brand"><Link href="/" className="home-brand"><span className="brand-mark">A</span><strong>A-One Tours & Travels</strong></Link></div><Card className="login-card reset-card"><p className="eyebrow">Account recovery</p>{step === 0 && <><h1>Reset your password</h1><p className="muted">Enter your email and we’ll send a one-time reset code.</p><form onSubmit={submitEmail}><Input label="Email address" id="reset-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} disabled={loading} />{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={loading}>{loading ? "Sending code..." : "Send reset code"}</Button></form></>}{step === 1 && <><h1>Check your email</h1><p className="muted">{notice}</p><form onSubmit={submitOtp}><Input label="6-digit reset code" id="reset-otp" inputMode="numeric" maxLength={6} value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, ""))} disabled={loading} />{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={loading}>{loading ? "Confirming..." : "Confirm code"}</Button></form><button className="text-link reset-back" type="button" onClick={() => setStep(0)}>Use a different email</button></>}{step === 2 && <><h1>Choose a new password</h1><p className="muted">Your code is confirmed. Choose a password you haven’t used before.</p><form onSubmit={submitPassword}><Input label="New password" id="new-password" type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={loading} /><Input label="Confirm password" id="confirm-password" type="password" autoComplete="new-password" value={passwordConfirmation} onChange={(event) => setPasswordConfirmation(event.target.value)} disabled={loading} />{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={loading}>{loading ? "Updating password..." : "Reset password"}</Button></form></>}{step === 3 && <><h1>Password updated</h1><p className="muted">Your password has been reset successfully. You can sign in with it now.</p><Link className="button button-primary reset-login" href="/login">Return to sign in</Link></>}</Card><p className="auth-switch"><Link href="/login">Back to sign in</Link></p></div>;
}
